apiVersion: 1

datasources:
  - name: MongoDB
    type: mongodb-datasource
    access: proxy
    url: mongodb://admin:password123@mongodb:27017/zero_bot
    database: zero_bot
    isDefault: false
    editable: true
    jsonData:
      authType: "credentials"
      defaultDatabase: "zero_bot"
    secureJsonData:
      username: "admin"
      password: "password123"

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    isDefault: false
    editable: true
    jsonData:
      client: "standalone"
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    secureJsonData:
      password: "redis123"

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      queryTimeout: "60s"
      timeInterval: "15s" 