# Generated by Django 5.0 on 2026-02-20 03:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BotPassport",
            fields=[
                (
                    "bot_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique bot identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "solana_nft_address",
                    models.CharField(
                        blank=True,
                        help_text="Solana NFT mint address (canonical)",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "ton_nft_address",
                    models.CharField(
                        blank=True,
                        help_text="TON NFT address (UI wrapper)",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Bot display name", max_length=100),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Bot description"),
                ),
                (
                    "experience_points",
                    models.PositiveIntegerField(
                        default=0, help_text="XP earned through training and usage"
                    ),
                ),
                (
                    "training_level",
                    models.PositiveIntegerField(
                        default=1, help_text="Current training level (1-100)"
                    ),
                ),
                (
                    "state",
                    models.JSONField(
                        default=dict, help_text="Mirror of Solana PDA state"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether bot is active and operational"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Django user who owns this bot",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_passports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bot_passports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonalityInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_prompt_override",
                    models.TextField(
                        blank=True,
                        help_text="Custom prompt override for this bot instance",
                    ),
                ),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this personality instance is active",
                    ),
                ),
                (
                    "passport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personality_instances",
                        to="bot_core.botpassport",
                    ),
                ),
            ],
            options={
                "db_table": "personality_instances",
            },
        ),
        migrations.CreateModel(
            name="SkillInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Skill-specific configuration"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether skill is currently active"
                    ),
                ),
                (
                    "passport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_installations",
                        to="bot_core.botpassport",
                    ),
                ),
            ],
            options={
                "db_table": "skill_installations",
            },
        ),
        migrations.CreateModel(
            name="BotState",
            fields=[
                (
                    "passport",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="local_state",
                        serialize=False,
                        to="bot_core.botpassport",
                    ),
                ),
                (
                    "conversation_context",
                    models.JSONField(
                        default=dict,
                        help_text="Current conversation context and memory",
                    ),
                ),
                (
                    "training_data_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of training corpus for integrity",
                        max_length=64,
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, help_text="Last sync with Solana PDA", null=True
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("synced", "Synced"),
                            ("pending", "Sync Pending"),
                            ("conflict", "Sync Conflict"),
                            ("error", "Sync Error"),
                        ],
                        default="pending",
                        help_text="Synchronization status with blockchain",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "bot_states",
                "indexes": [
                    models.Index(
                        fields=["sync_status"], name="bot_states_sync_st_3860d2_idx"
                    ),
                    models.Index(
                        fields=["last_synced_at"], name="bot_states_last_sy_207d77_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="botpassport",
            index=models.Index(fields=["owner"], name="bot_passpor_owner_i_807a54_idx"),
        ),
        migrations.AddIndex(
            model_name="botpassport",
            index=models.Index(
                fields=["solana_nft_address"], name="bot_passpor_solana__5e7271_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="botpassport",
            index=models.Index(
                fields=["ton_nft_address"], name="bot_passpor_ton_nft_358faa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="botpassport",
            index=models.Index(
                fields=["is_active"], name="bot_passpor_is_acti_3575c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="botpassport",
            index=models.Index(
                fields=["training_level"], name="bot_passpor_trainin_50f496_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personalityinstance",
            index=models.Index(
                fields=["passport"], name="personality_passpor_d0a950_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personalityinstance",
            index=models.Index(
                fields=["activated_at"], name="personality_activat_eeeb14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personalityinstance",
            index=models.Index(
                fields=["is_active"], name="personality_is_acti_3a5deb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skillinstallation",
            index=models.Index(
                fields=["passport"], name="skill_insta_passpor_2892b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skillinstallation",
            index=models.Index(
                fields=["installed_at"], name="skill_insta_install_1dde1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skillinstallation",
            index=models.Index(
                fields=["is_active"], name="skill_insta_is_acti_1bba34_idx"
            ),
        ),
    ]
