# Generated by Django 5.0 on 2026-02-20 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_core", "0001_initial"),
        ("personalities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="botpassport",
            name="personality",
            field=models.ForeignKey(
                blank=True,
                help_text="Active personality",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bot_instances",
                to="personalities.personality",
            ),
        ),
        migrations.AddField(
            model_name="personalityinstance",
            name="personality",
            field=models.ForeignKey(
                blank=True,
                help_text="Personality applied to this bot",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="personalities.personality",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="personalityinstance",
            unique_together={("passport", "personality")},
        ),
        migrations.AddIndex(
            model_name="personalityinstance",
            index=models.Index(
                fields=["personality"], name="personality_persona_1bd63b_idx"
            ),
        ),
    ]
