# Generated by Django 5.0 on 2026-02-20 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot_core", "0002_botpassport_personality_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SkillInstallation",
        ),
    ]
