# Generated by Django 5.0 on 2026-02-20 04:04

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., 'Assistant', 'Creative', 'Technical')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Category description"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Hex color code for UI display",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Emoji or icon for category display",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether category is active"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Sort order for display"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Personality Categories",
                "db_table": "personality_categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Personality",
            fields=[
                (
                    "personality_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique personality identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Personality name (e.g., 'Zero', 'Assistant', 'Creative')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of personality traits and behavior"
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="Base system prompt that defines personality behavior"
                    ),
                ),
                (
                    "langflow_flow_id",
                    models.CharField(
                        blank=True,
                        help_text="Langflow flow ID for dynamic prompt management",
                        max_length=255,
                    ),
                ),
                (
                    "price_ia_coin",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Price in IA-coin to use this personality",
                        max_digits=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether personality is available for use",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a system-provided personality",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Whether personality is publicly available",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional personality metadata (voice, avatar, etc.)",
                    ),
                ),
                (
                    "total_installations",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this personality has been installed",
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total revenue generated from this personality",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="User who created this personality",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_personalities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Personalities",
                "db_table": "personalities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonalityCategoryMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personality_memberships",
                        to="personalities.personalitycategory",
                    ),
                ),
                (
                    "personality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_memberships",
                        to="personalities.personality",
                    ),
                ),
            ],
            options={
                "db_table": "personality_category_memberships",
            },
        ),
        migrations.CreateModel(
            name="PersonalityRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(help_text="Rating from 1 to 5 stars"),
                ),
                (
                    "review",
                    models.TextField(blank=True, help_text="Optional review text"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "personality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="personalities.personality",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personality_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "personality_ratings",
            },
        ),
        migrations.CreateModel(
            name="PersonalityTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Template description and use cases"),
                ),
                (
                    "system_prompt_template",
                    models.TextField(
                        help_text="System prompt template with placeholders"
                    ),
                ),
                (
                    "metadata_template",
                    models.JSONField(
                        default=dict, help_text="Default metadata structure"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether template is available for use"
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of personalities created from this template",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default category for personalities created from this template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="personalities.personalitycategory",
                    ),
                ),
            ],
            options={
                "db_table": "personality_templates",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="personality",
            index=models.Index(fields=["name"], name="personaliti_name_811728_idx"),
        ),
        migrations.AddIndex(
            model_name="personality",
            index=models.Index(
                fields=["creator"], name="personaliti_creator_95a305_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personality",
            index=models.Index(
                fields=["is_active"], name="personaliti_is_acti_128db1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personality",
            index=models.Index(
                fields=["is_public"], name="personaliti_is_publ_60e02f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personality",
            index=models.Index(
                fields=["is_system"], name="personaliti_is_syst_424645_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personality",
            index=models.Index(
                fields=["price_ia_coin"], name="personaliti_price_i_aabbb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personality",
            index=models.Index(
                fields=["total_installations"], name="personaliti_total_i_3dc139_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personalitycategorymembership",
            index=models.Index(
                fields=["personality"], name="personality_persona_91762a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personalitycategorymembership",
            index=models.Index(
                fields=["category"], name="personality_categor_72617f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="personalitycategorymembership",
            unique_together={("personality", "category")},
        ),
        migrations.AddIndex(
            model_name="personalityrating",
            index=models.Index(
                fields=["personality"], name="personality_persona_1ae657_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personalityrating",
            index=models.Index(fields=["user"], name="personality_user_id_71a23e_idx"),
        ),
        migrations.AddIndex(
            model_name="personalityrating",
            index=models.Index(fields=["rating"], name="personality_rating_cd9f84_idx"),
        ),
        migrations.AddIndex(
            model_name="personalityrating",
            index=models.Index(
                fields=["created_at"], name="personality_created_8f8f1e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="personalityrating",
            unique_together={("personality", "user")},
        ),
        migrations.AddIndex(
            model_name="personalitytemplate",
            index=models.Index(
                fields=["is_active"], name="personality_is_acti_102974_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personalitytemplate",
            index=models.Index(
                fields=["category"], name="personality_categor_5555bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personalitytemplate",
            index=models.Index(
                fields=["usage_count"], name="personality_usage_c_cf0800_idx"
            ),
        ),
    ]
