# Generated by Django 5.0 on 2026-02-20 04:25

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bot_core", "0003_remove_skill_installation_placeholder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название категории навыков",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Описание категории"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Emoji иконка категории", max_length=10
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Hex цвет для UI отображения",
                        max_length=7,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Активна ли категория"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Порядок сортировки"
                    ),
                ),
            ],
            options={
                "db_table": "skill_categories",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="skill_categ_is_acti_652cfb_idx"
                    ),
                    models.Index(
                        fields=["sort_order"], name="skill_categ_sort_or_41cc31_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Название навыка", max_length=200)),
                ("description", models.TextField(help_text="Описание навыка")),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", help_text="Версия навыка", max_length=20
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Теги для поиска"
                    ),
                ),
                (
                    "price_ia_coins",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Цена в IA-Coins",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(default=False, help_text="Бесплатный навык"),
                ),
                (
                    "revenue_share_creator",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("60.00"),
                        help_text="Процент дохода создателю",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "execution_type",
                    models.CharField(
                        choices=[
                            ("api_call", "API вызов"),
                            ("code_execution", "Выполнение кода"),
                            ("langflow_node", "Langflow узел"),
                            ("webhook", "Webhook"),
                            ("database_query", "Запрос к БД"),
                        ],
                        default="api_call",
                        help_text="Тип выполнения навыка",
                        max_length=50,
                    ),
                ),
                (
                    "handler_module",
                    models.CharField(
                        blank=True,
                        help_text="Python модуль обработчика",
                        max_length=200,
                    ),
                ),
                (
                    "api_endpoint",
                    models.URLField(blank=True, help_text="API endpoint для вызова"),
                ),
                ("webhook_url", models.URLField(blank=True, help_text="Webhook URL")),
                (
                    "langflow_node_id",
                    models.CharField(
                        blank=True, help_text="ID узла в Langflow", max_length=100
                    ),
                ),
                (
                    "config_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON схема конфигурации навыка",
                    ),
                ),
                (
                    "requirements",
                    models.JSONField(
                        blank=True, default=list, help_text="Требования для установки"
                    ),
                ),
                (
                    "capabilities",
                    models.JSONField(
                        blank=True, default=list, help_text="Возможности навыка"
                    ),
                ),
                (
                    "solana_registry_address",
                    models.CharField(
                        blank=True,
                        help_text="Адрес в Solana Skill Registry",
                        max_length=44,
                        null=True,
                    ),
                ),
                (
                    "solana_tx_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash транзакции регистрации в Solana",
                        max_length=88,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending_review", "На модерации"),
                            ("approved", "Одобрен"),
                            ("rejected", "Отклонен"),
                            ("active", "Активен"),
                            ("deprecated", "Устарел"),
                        ],
                        default="draft",
                        help_text="Статус навыка",
                        max_length=20,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Доступен в публичном маркетплейсе"
                    ),
                ),
                (
                    "moderation_notes",
                    models.TextField(blank=True, help_text="Заметки модератора"),
                ),
                (
                    "total_installations",
                    models.PositiveIntegerField(
                        default=0, help_text="Общее количество установок"
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Общий доход",
                        max_digits=12,
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Средняя оценка",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("5.00")),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата публикации в маркетплейсе",
                        null=True,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="Создатель навыка",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Основная категория навыка",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skills",
                        to="skills.skillcategory",
                    ),
                ),
            ],
            options={
                "db_table": "skills",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_paid",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Цена, уплаченная за навык",
                        max_digits=10,
                    ),
                ),
                (
                    "payment_currency",
                    models.CharField(
                        default="IA_COINS", help_text="Валюта платежа", max_length=10
                    ),
                ),
                (
                    "solana_payment_tx",
                    models.CharField(
                        blank=True,
                        help_text="Hash транзакции оплаты в Solana",
                        max_length=88,
                        null=True,
                    ),
                ),
                (
                    "solana_install_tx",
                    models.CharField(
                        blank=True,
                        help_text="Hash транзакции установки в Solana",
                        max_length=88,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("processing", "Обрабатывается"),
                            ("completed", "Завершена"),
                            ("failed", "Ошибка"),
                            ("refunded", "Возврат"),
                        ],
                        default="pending",
                        help_text="Статус установки",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Конфигурация навыка для данного бота",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, help_text="Включен ли навык"),
                ),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot_passport",
                    models.ForeignKey(
                        help_text="Бот, на который установлен навык",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_installations",
                        to="bot_core.botpassport",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        help_text="Покупатель навыка",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        help_text="Установленный навык",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "db_table": "skill_installations",
                "ordering": ["-installed_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        help_text="Оценка от 1 до 5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review", models.TextField(blank=True, help_text="Текстовый отзыв")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "installation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Связанная установка навыка",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skills.skillinstallation",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        help_text="Оцениваемый навык",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="skills.skill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, оставивший оценку",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "skill_ratings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["creator"], name="skills_creator_201a0a_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["category"], name="skills_categor_0124d8_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["status"], name="skills_status_c09232_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["is_public"], name="skills_is_publ_71aaed_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["price_ia_coins"], name="skills_price_i_540add_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["total_installations"], name="skills_total_i_a28a07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["average_rating"], name="skills_average_fec4a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["created_at"], name="skills_created_f16f3d_idx"),
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.CheckConstraint(
                check=models.Q(("price_ia_coins__gte", 0)), name="positive_price"
            ),
        ),
        migrations.AddIndex(
            model_name="skillinstallation",
            index=models.Index(fields=["skill"], name="skill_insta_skill_i_e906cd_idx"),
        ),
        migrations.AddIndex(
            model_name="skillinstallation",
            index=models.Index(
                fields=["bot_passport"], name="skill_insta_bot_pas_f7a08a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skillinstallation",
            index=models.Index(fields=["buyer"], name="skill_insta_buyer_i_2f67fb_idx"),
        ),
        migrations.AddIndex(
            model_name="skillinstallation",
            index=models.Index(fields=["status"], name="skill_insta_status_e4fee3_idx"),
        ),
        migrations.AddIndex(
            model_name="skillinstallation",
            index=models.Index(
                fields=["installed_at"], name="skill_insta_install_1dde1d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skillinstallation",
            unique_together={("skill", "bot_passport")},
        ),
        migrations.AddIndex(
            model_name="skillrating",
            index=models.Index(fields=["skill"], name="skill_ratin_skill_i_c6c638_idx"),
        ),
        migrations.AddIndex(
            model_name="skillrating",
            index=models.Index(fields=["user"], name="skill_ratin_user_id_df8a1b_idx"),
        ),
        migrations.AddIndex(
            model_name="skillrating",
            index=models.Index(fields=["rating"], name="skill_ratin_rating_7eb161_idx"),
        ),
        migrations.AddIndex(
            model_name="skillrating",
            index=models.Index(
                fields=["created_at"], name="skill_ratin_created_fb345f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skillrating",
            unique_together={("skill", "user")},
        ),
    ]
